# Assignment 1 - Gender Column Cleaning

In [7]:
# Mounting Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted successfully")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive mounted successfully

In [2]:
# Confirming python version
import sys
print(f"Python version: {sys.version}")

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [3]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Libraries imported successfully!")

Libraries imported successfully!

In [52]:
# Loading dataset from google drive location
FILE_PATH = '/content/drive/MyDrive/Carisurg_Week0/EmergencyTriageDataset_Reduced_Dirty.csv'

# Reading the csv dataset using pandas
df_raw = pd.read_csv(FILE_PATH)

# Printing the number of rows and columns in the dataset
print(f"Dataset loaded: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")

# Printing column headings
print(f"Columns:{list(df_raw.columns)}")

Dataset loaded: 2205 rows x 11 columns
Columns:['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [53]:
# Observing the first 10 rows of dataset
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [54]:
# Printing datatypes of each column
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [55]:
# Printing the unique values in the gender column
print("Unique values in Gender:")
print(df_raw['Gender'].unique())

# Printing the total number of unique values in the gender column
print(f"\nTotal unique values: {df_raw['Gender'].nunique()}")

Unique values in Gender:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Total unique values: 6

In [56]:
# Printing the numbers of each unique gender value in the dataset
print("Gender value counts:")
print(df_raw['Gender'].value_counts())

Gender value counts:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [57]:
# Mapping each unique variant in the dataset to an integer value of either 1 or 0
# 1 represents male and 0 represents female

gender_map = {
    'Male':   1,
    'MALE':   1,
    '1':      1,
    'Female': 0,
    'FEMALE': 0,
    '0':      0
}

# Applying the mapping to create a new, clean column
df_raw['Gender_Clean'] = df_raw['Gender'].map(gender_map)

# Verifying clean column by printing the nmber of 1 and 0 values in the gender column
print("After cleaning:")
print(df_raw['Gender_Clean'].value_counts())

# Verifying that there are no non numerical values in the cleaned gender column
print(f"\nAny NaN values? {df_raw['Gender_Clean'].isnull().sum()}")

After cleaning:
Gender_Clean
1    1176
0    1029
Name: count, dtype: int64

Any NaN values? 0

In [58]:
# Dropping the original dirty column and replace with clean one

df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_Clean': 'Gender'})

# Confirming the result by printing the clean gender column
print("Column 'Gender' after cleaning:")
print(df_raw['Gender'].value_counts())
print(f"Data type: {df_raw['Gender'].dtype}")
df_raw.head(10)

Column 'Gender' after cleaning:
Gender
1    1176
0    1029
Name: count, dtype: int64
Data type: int64

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0
5   6   42  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0       1
6   7   75  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0       0
7   8   25  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0       1
8   9   67  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0       0
9  11   82  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0       0